name: 🐞 Bug Report
description: Report program errors or abnormal behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your feedback! Please fill in the following information as completely as possible.

  - type: input
    id: environment
    attributes:
      label: Environment Information
      description: System, browser, or runtime environment details
      placeholder: e.g., macOS 14 / Chrome 125 / Node.js v20
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please list the exact steps to reproduce the issue
      placeholder: |
        1. Open the homepage
        2. Click the settings button
        3. Console error appears...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen under normal circumstances?
      placeholder: The settings page should open normally
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The page is blank and shows an error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs or Screenshots
      description: Please paste error logs or screenshots here if available
