blank_issues_enabled: false
contact_links:
  - name: 💬 社区讨论 (Community Discussions)
    url: https://github.com/maginapp/neck-upgrade/discussions
    about: 如非 bug 或功能建议，请在 Discussions 提问 (If this is not a bug or feature request, please ask in Discussions.)
